extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.licm]
pipeline = [
    "bril2json",
    "python ../compiler/licm.py",
    "brili -p {args}",
]
